name: live_coding
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.3.0
